-- Enable RLS
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- 1. PROFILES (Users)
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text not null,
  full_name text,
  subscription_plan text default 'free', -- 'free', 'premium'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table profiles enable row level security;
drop policy if exists "Users can view own profile" on profiles;
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
drop policy if exists "Users can update own profile" on profiles;
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- 2. USER STATS (Initialized to 0)
create table if not exists user_stats (
  user_id uuid references auth.users on delete cascade not null primary key,
  messages_processed bigint default 0,
  deleted_messages_captured bigint default 0,
  statuses_saved bigint default 0,
  ai_replies_sent bigint default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);
alter table user_stats enable row level security;
drop policy if exists "Users can view own stats" on user_stats;
create policy "Users can view own stats" on user_stats for select using (auth.uid() = user_id);
drop policy if exists "Users can update own stats" on user_stats;
create policy "Users can update own stats" on user_stats for update using (auth.uid() = user_id);

-- Trigger for new users (Profile + Stats Init)
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  -- Create Profile (skip if exists)
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name')
  on conflict (id) do nothing;
  
  -- Initialize Stats to 0 (skip if exists)
  insert into public.user_stats (user_id, messages_processed, deleted_messages_captured, statuses_saved, ai_replies_sent)
  values (new.id, 0, 0, 0, 0)
  on conflict (user_id) do nothing;
  
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to avoid duplication errors on re-run
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. WHATSAPP SESSIONS (Baileys Auth)
create table if not exists whatsapp_sessions (
  session_id text not null,
  key text not null,
  data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  primary key (session_id, key)
);
alter table whatsapp_sessions enable row level security;
drop policy if exists "Service role full access" on whatsapp_sessions;
create policy "Service role full access" on whatsapp_sessions for all to service_role using (true) with check (true);

-- 4. CONTACTS SETTINGS (Ghost Mode per contact)
create table if not exists contacts_settings (
  id bigint generated by default as identity primary key,
  session_id text not null,
  jid text not null, -- Contact ID (e.g. 123456@s.whatsapp.net)
  name text,
  ghost_mode boolean default false, 
  auto_reply boolean default false,
  custom_prefix text, 
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(session_id, jid)
);
alter table contacts_settings enable row level security;
drop policy if exists "Service role full access contacts" on contacts_settings;
create policy "Service role full access contacts" on contacts_settings for all to service_role using (true) with check (true);

-- 5. SCHEDULED TASKS (Cron)
create table if not exists scheduled_tasks (
  id bigint generated by default as identity primary key,
  session_id text not null,
  type text not null check (type in ('message', 'status')), 
  recipient text, 
  content text,
  media_url text, 
  scheduled_at timestamp with time zone not null,
  status text default 'pending' check (status in ('pending', 'sent', 'failed')),
  error text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table scheduled_tasks enable row level security;
drop policy if exists "Service role full access tasks" on scheduled_tasks;
create policy "Service role full access tasks" on scheduled_tasks for all to service_role using (true) with check (true);

-- 6. MEDIA ARCHIVES (Anti-Delete / Saved Status)
create table if not exists media_archives (
  id bigint generated by default as identity primary key,
  session_id text not null,
  message_id text,
  chat_id text,
  sender_name text,
  media_type text, 
  media_url text not null, 
  caption text,
  is_deleted_msg boolean default false, 
  is_status boolean default false, 
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table media_archives enable row level security;
drop policy if exists "Service role full access media" on media_archives;
create policy "Service role full access media" on media_archives for all to service_role using (true) with check (true);
